% planning/backlog.pl -- executable mirror of the GitHub work queue.
% NOT loaded by the Zara runtime; GitHub issues remain authoritative.
% Generated by scripts/import-backlog.py from live GitHub issue state.
% Hand-curated sections preserved from the previous file: phase/2, pr/4.
%
% Usage:
%   nix develop -c swipl -s planning/backlog.pl -g "next(I), writeln(I)" -t halt.
%   nix develop -c swipl -s planning/backlog.pl  % then: next(I). queue(Q). blockers(122, Bs).

% Closed issues referenced by dependency edges, phases or epics.
closed(2). closed(3). closed(4). closed(5). closed(6). closed(7). closed(8). closed(9). closed(17). closed(28). closed(124). closed(128). closed(129). closed(130). closed(131). closed(132). closed(133). closed(139). closed(154). closed(155). closed(156). closed(157). closed(170). closed(171). closed(191). closed(195). closed(209).

% Open issues: issue(Id, Priority, Status, ShortTitle).
issue(87, p1, open, "P1 — add Linux global shortcut backends for Wayland and X11").
issue(88, p1, open, "P1 — add explicit desktop context attachments and permission UI").
issue(89, p1, open, "P1 — render structured tool execution and user approvals in chat").
issue(90, p1, open, "P1 — integrate existing voice states and desktop notifications").
issue(91, p2, open, "P2 — add an extensible command palette and desktop capability registry").
issue(92, p2, open, "P2 — add desktop settings and sanitized diagnostics").
issue(93, p2, open, "P2 — add an advanced Prolog reasoning inspector").
issue(94, p2, open, "P2 — unify Zarathushtra Pets with the desktop event stream and tray").
issue(95, p3, open, "P3 — package Zara Desktop and harden platform lifecycle behavior").
issue(122, p0, open, "P0 — add a bounded utterance rewriter before Prolog intent resolution").
issue(134, p0, open, "P0 release gate — prove Zara daemon can replace the core ChatGPT Voice workflow safely").
issue(149, p1, open, "P1 — publish Nix-built `zara-server` OCI image to GHCR").
issue(158, p1, open, "P1 — add server `api_service` providers and split semantic/server/device Prolog configuration").
issue(159, p1, open, "P1 — extend `ZARA/1` with bounded client capability advertisement and typed device action lifecycle").
issue(160, p1, open, "P1 — make RuntimeHost own semantic command routing and remove duplicated LLM prompt authority").
issue(161, p1, open, "P1 release gate — adversarially prove semantic dialogue/provider/device routing across reconnect and concurrency").
issue(162, p1, open, "P1 — define versioned principal-scoped persistence for user-authored semantic commands").
issue(163, p1, open, "P1 — compile user-authored command definitions into validated `IntentFrame`/capability plans").
issue(164, p1, open, "P1 — add voice/text command-authoring dialogue for create, inspect, edit, delete, dry-run and undo").
issue(165, p1, open, "P1 — support parameterized user commands, collisions, revocation and atomic hot reload").
issue(166, p1, open, "P1 — define one declarative voice-fixture manifest for realistic command/dialogue recordings").
issue(167, p1, open, "P1 — build `zara-record-voice-fixtures` with guided realistic timing and audio quality validation").
issue(168, p1, open, "P1 — check in the representative real speech corpus and run VAD/STT -> dialogue/capability regression tests").
issue(169, p1, open, "P1 human release gate — create and exercise new Zara commands by real voice on live hardware").
issue(172, p2, open, "P2 — extract and prove a portable shared Prolog semantic core on Linux and Android").
issue(173, p2, open, "P2 — implement authenticated Android `ZARA/1` client enrollment, reconnect and session continuity").
issue(174, p2, open, "P2 — implement the closed Android device-capability registry and typed action adapters").
issue(175, p2, open, "P2 — implement Android microphone/wake/manual activation, streamed playback and cross-process barge-in").
issue(176, p2, open, "P2 — define Android local/degraded Prolog behavior without duplicating the server assistant").
issue(177, p2, open, "P2 — prove programmable user commands have Linux/Android semantic parity and provider-specific execution").
issue(178, p2, open, "P2 release gate — adversarial Android lifecycle, security, resource and cross-platform parity matrix").
issue(179, p2, open, "P2 human release gate — prove Zara Android on a real device with embedded Prolog, live voice and typed actions").
issue(180, p1, open, "P1 — harden container state/config/key volumes, non-root execution, and read-only-root policy").
issue(181, p1, open, "P1 — add deterministic container lifecycle, readiness, persistence, restart, and upgrade integration gates").
issue(182, p2, open, "P2 — define container model/cache/plugin policy and maintained Docker/Podman/Compose deployment examples").
issue(183, p1, open, "P1 release gate — prove container image secrets, listener policy, provenance, and capability placement").
issue(196, p1, open, "P1 — implement Android Assistant role and voice-interaction service surface").
issue(197, p1, open, "P1 — build the modern Compose Zara application shell on shared runtime state").
issue(198, p1, open, "P1 — establish one hot-reloadable Prolog authority for Android semantics and providers").
issue(199, p1, open, "P1 — add typed Android app, browser, YouTube and ChatGPT adapters").
issue(200, p1, open, "P1 — implement Android timer, alarm and dual-calendar capability adapters").
issue(201, p1, open, "P1 — add a fail-closed Termux named-action adapter and result lifecycle").
issue(202, p1, open, "P1 — implement the server-side SmartThings OAuth, device and event provider").
issue(203, p1, open, "P1 — harden Samsung assistant background voice, audio and reconnect lifecycle").
issue(204, p1, open, "P1 gate — prove Prolog-defined cross-component commands without APK rebuild").
issue(205, p0, open, "P0 gate — adversarial Android and Samsung lifecycle/security integration matrix").
issue(206, p0, open, "P0 hardware release — real Samsung acceptance and exact downloadable Zara APK").
issue(216, p1, open, "P1 — define provider-neutral transcript normalization contract and raw/normalized runtime semantics").
issue(217, p1, open, "P1 — implement local S1-mini transcript normalizer backend").
issue(218, p1, open, "P1 — add transcript-normalizer configuration, selection, status and diagnostics").
issue(219, p1, open, "P1 — wire transcript normalization into voice, dictation and semantic routing before #122").
issue(220, p1, open, "P1 release gate — prove transcript normalization preserves intent, privacy and voice latency").
issue(238, p2, open, "P2 — implement plugin download and installation from the zara-plugins registry").
issue(240, p2, open, "P2 — let the Zara flake consume and configure zara-plugins").
issue(244, p1, open, "P1 — migrate the zara wake listener onto the daemon ZARA/1 voice client with principal-scoped memory").

% Roadmap order: phase(N, OrderedIssueIds). Rank = N*100 + index.
phase(0, [17]).                                    % regression: always first
phase(1, [134, 139]).                              % daemon: consumed queue tail
phase(2, [28, 29, 30, 31, 51]).                    % duplex voice + release gate + context
phase(3, [124, 216, 217, 218, 219, 220, 122]).     % model + normalization chain
phase(4, [149, 180, 181, 182, 183]).               % container distribution
phase(5, [154, 155, 156, 157, 158, 159, 160, 161]).% semantic intents
phase(6, [162, 163, 164, 165, 166, 167, 168, 169]).% programmable commands
phase(7, [170, 171, 172, 173, 174, 175, 176, 177, 178, 179]). % android client
phase(8, [195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206]). % samsung
phase(9, [87, 88, 89, 90, 91, 92, 93, 94, 95, 56]).% desktop + recall

% Dependency edges (only edges that gate eligibility).
depends_on(134, 130).
depends_on(134, 131).
depends_on(134, 132).
depends_on(134, 133).
depends_on(158, 157).
depends_on(159, 129).
depends_on(159, 130).
depends_on(159, 158).
depends_on(160, 159).
depends_on(161, 160).
depends_on(162, 131).
depends_on(162, 150).
depends_on(162, 154).
depends_on(162, 157).
depends_on(163, 157).
depends_on(163, 162).
depends_on(164, 132).
depends_on(164, 133).
depends_on(164, 155).
depends_on(164, 163).
depends_on(165, 164).
depends_on(166, 132).
depends_on(166, 156).
depends_on(166, 165).
depends_on(167, 166).
depends_on(168, 132).
depends_on(168, 165).
depends_on(168, 167).
depends_on(169, 132).
depends_on(169, 133).
depends_on(169, 134).
depends_on(169, 161).
depends_on(169, 168).
depends_on(172, 156).
depends_on(172, 171).
depends_on(173, 133).
depends_on(173, 159).
depends_on(173, 172).
depends_on(174, 159).
depends_on(174, 173).
depends_on(175, 132).
depends_on(175, 170).
depends_on(175, 173).
depends_on(176, 172).
depends_on(176, 173).
depends_on(176, 174).
depends_on(177, 165).
depends_on(177, 174).
depends_on(177, 176).
depends_on(178, 175).
depends_on(178, 177).
depends_on(179, 134).
depends_on(179, 169).
depends_on(179, 178).
depends_on(180, 149).
depends_on(181, 180).
depends_on(182, 181).
depends_on(183, 161).
depends_on(183, 182).
depends_on(196, 171).
depends_on(196, 173).
depends_on(196, 195).
depends_on(197, 171).
depends_on(197, 173).
depends_on(197, 195).
depends_on(198, 172).
depends_on(198, 174).
depends_on(198, 177).
depends_on(198, 195).
depends_on(199, 159).
depends_on(199, 174).
depends_on(199, 198).
depends_on(200, 159).
depends_on(200, 174).
depends_on(200, 198).
depends_on(201, 159).
depends_on(201, 174).
depends_on(201, 198).
depends_on(202, 158).
depends_on(202, 195).
depends_on(203, 132).
depends_on(203, 175).
depends_on(203, 196).
depends_on(203, 197).
depends_on(204, 177).
depends_on(204, 198).
depends_on(204, 199).
depends_on(204, 200).
depends_on(204, 201).
depends_on(204, 202).
depends_on(205, 178).
depends_on(205, 196).
depends_on(205, 197).
depends_on(205, 198).
depends_on(205, 199).
depends_on(205, 200).
depends_on(205, 201).
depends_on(205, 202).
depends_on(205, 203).
depends_on(205, 204).
depends_on(206, 134).
depends_on(206, 179).
depends_on(206, 205).
depends_on(217, 216).
depends_on(218, 216).
depends_on(218, 217).
depends_on(219, 216).
depends_on(219, 217).
depends_on(219, 218).
depends_on(220, 219).
depends_on(244, 134).

% Epics: epic_children(EpicId, ChildIds).
epic_children(127, [128,129,130,131,132,133,134,191,209,244]).
epic_children(150, [154,155,156,157,158,159,160,161]).
epic_children(151, [162,163,164,165,166,167,168,169]).
epic_children(152, [170,171,172,173,174,175,176,177,178,179,194]).
epic_children(153, [180,181,182,183]).
epic_children(194, [195,196,197,198,199,200,201,202,203,204,205,206]).
epic_children(215, [216,217,218,219,220]).

% Open PRs: pr(Id, Issue, Status, CiDate, Note). CiDate = none | Y-M-D.
pr(138, none, open,  none,        parked_rebase_post_daemon_factcheck).
pr(222, none, open,  none,        parked_design_direction_decision_needed).
pr(223, 127,  open,  none,        parked_rebase_zara1_contract_reconciliation).

master_last_merge(2026-08-31).

% ---- Rules ----
open_issue(I) :- issue(I, _, open, _).
done(I) :- issue(I, _, done, _).
done(I) :- closed(I).

satisfied(I) :- \+ (depends_on(I, D), \+ done(D)).
eligible(I)  :- open_issue(I), satisfied(I).
blocked(I)   :- open_issue(I), \+ satisfied(I).
waiting_on(I, D) :- depends_on(I, D), \+ done(D).
blockers(I, Ds) :- setof(D, waiting_on(I, D), Ds).

phase_rank(I, R) :- phase(P, L), nth0(Idx, L, I), R is P * 100 + Idx.
next(I) :- setof(R-I, (eligible(I), phase_rank(I, R)), [_-I|_]).
queue(Q) :- setof(R-I, (eligible(I), phase_rank(I, R)), Q).

epic_progress(E, DoneCount, Total) :-
    epic_children(E, Cs),
    length(Cs, Total),
    include([C]>>done(C), Cs, Ds),
    length(Ds, DoneCount).

open_pr(P) :- pr(P, _, open, _, _).
stale_ci(P) :-
    pr(P, _, _, D, _),
    D \== none,
    master_last_merge(M),
    D @< M.
missing_ci(P) :- open_pr(P), pr(P, _, _, none, _).
