package ai.zara.ui.complication

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class PrologComplicationTemplateTest {
    @Test
    fun compilesShortTextTemplate() {
        val template = PrologComplicationTemplateCompiler.compile(
            """
                % generated by an LLM, validated before transfer
                complication_template(zara_status, short_text).
                complication_text(zara_status, "Ready").
                complication_title(zara_status, "Zara").
                complication_description(zara_status, "Assistant status").
            """.trimIndent()
        )

        assertEquals("zara_status", template.id)
        assertEquals(PrologComplicationType.SHORT_TEXT, template.type)
        assertEquals("Ready", template.text)
        assertEquals("Zara", template.title)
    }

    @Test
    fun compilesBoundedRange() {
        val template = PrologComplicationTemplateCompiler.compile(
            """
                complication_template(battery, ranged_value).
                complication_text(battery, "72%").
                complication_description(battery, "Phone battery").
                complication_range(battery, 72, 0, 100).
            """.trimIndent()
        )

        assertEquals(72f, template.rangeValue)
        assertEquals(0f, template.rangeMin)
        assertEquals(100f, template.rangeMax)
    }

    @Test
    fun rejectsRulesDirectivesAndUnknownFacts() {
        assertTrue(
            runCatching {
                PrologComplicationTemplateCompiler.compile(
                    "complication_template(x, short_text) :- shell(evil)."
                )
            }.isFailure
        )
        assertTrue(
            runCatching {
                PrologComplicationTemplateCompiler.compile(
                    ":- initialization(shell(evil))."
                )
            }.isFailure
        )
        assertTrue(
            runCatching {
                PrologComplicationTemplateCompiler.compile(
                    """
                        complication_template(x, short_text).
                        complication_text(x, "ok").
                        run_shell(x, "nope").
                    """.trimIndent()
                )
            }.isFailure
        )
    }

    @Test
    fun rejectsCrossTemplateFactsAndInvalidRanges() {
        assertTrue(
            runCatching {
                PrologComplicationTemplateCompiler.compile(
                    """
                        complication_template(one, short_text).
                        complication_text(two, "wrong id").
                    """.trimIndent()
                )
            }.isFailure
        )
        assertTrue(
            runCatching {
                PrologComplicationTemplateCompiler.compile(
                    """
                        complication_template(load, ranged_value).
                        complication_text(load, "120%").
                        complication_range(load, 120, 0, 100).
                    """.trimIndent()
                )
            }.isFailure
        )
    }
}
