concrete ZaraCanonical of Zara = open Prelude in {
  lincat Utterance, Request, Duration, Unit, App, Reply, Dig, Digits = {s : Str} ;
  lin
    IDig digit = digit ;
    IIDig digit rest = {s = digit.s ++ BIND ++ rest.s} ;
    D_0 = {s = "0"} ;
    D_1 = {s = "1"} ;
    D_2 = {s = "2"} ;
    D_3 = {s = "3"} ;
    D_4 = {s = "4"} ;
    D_5 = {s = "5"} ;
    D_6 = {s = "6"} ;
    D_7 = {s = "7"} ;
    D_8 = {s = "8"} ;
    D_9 = {s = "9"} ;
    Say request = request ;
    Address request = request ;
    Polite request = request ;
    AddressPolite request = request ;
    Greet = {s = "hello"} ;
    Help = {s = "help"} ;
    Identity = {s = "who are you"} ;
    Thanks = {s = "thanks"} ;
    Acknowledge = {s = "okay"} ;
    Cancel = {s = "cancel"} ;
    TimerMissing = {s = "timer"} ;
    OpenMissing = {s = "open"} ;
    SetTimer duration = {s = "timer" ++ duration.s} ;
    Followup duration = duration ;
    Correction duration = {s = "actually" ++ duration.s} ;
    OpenApp app = {s = "open" ++ app.s} ;
    DurationOf count unit = {s = count.s ++ unit.s} ;
    Seconds = {s = "seconds"} ;
    Minutes = {s = "minutes"} ;
    Hours = {s = "hours"} ;
    Settings = {s = "settings"} ;
    Termux = {s = "termux"} ;
    Firefox = {s = "firefox"} ;
    GreetingReply = {s = "greeting"} ;
    HelpReply = {s = "help"} ;
    ThanksReply = {s = "thanks"} ;
    AcknowledgedReply = {s = "acknowledged"} ;
    CancelledReply = {s = "cancelled"} ;
    DurationReply = {s = "clarify_duration"} ;
    TargetReply = {s = "clarify_target"} ;
    PendingReply = {s = "dispatch_required"} ;
    UnsupportedReply = {s = "unsupported"} ;
}
