#!/usr/bin/env python3
"""Regenerate planning/backlog.pl from live GitHub issue state.

GitHub issues remain authoritative (backlog.pl header contract). This script
imports what used to be hand-maintained: open issue facts, closed-issue
references, dependency edges from open-issue "Depends on:" lines, and epic
children from "Parent:" lines. Hand-curated sections (phase/2 roadmap order,
open pr/4 facts) are preserved verbatim from the existing file.

Usage:
  scripts/import-backlog.py [--repo OWNER/REPO] [--date YYYY-MM-DD] [--dry-run]

Output is deterministic: same inputs, same file.
"""

import argparse
import datetime
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKLOG = REPO_ROOT / "planning" / "backlog.pl"

HEADER = """% planning/backlog.pl -- executable mirror of the GitHub work queue.
% NOT loaded by the Zara runtime; GitHub issues remain authoritative.
% Generated by scripts/import-backlog.py from live GitHub issue state.
% Hand-curated sections preserved from the previous file: phase/2, pr/4.
%
% Usage:
%   nix develop -c swipl -s planning/backlog.pl -g "next(I), writeln(I)" -t halt.
%   nix develop -c swipl -s planning/backlog.pl  % then: next(I). queue(Q). blockers(122, Bs).
"""

RULES = """
% ---- Rules ----
open_issue(I) :- issue(I, _, open, _).
done(I) :- issue(I, _, done, _).
done(I) :- closed(I).

satisfied(I) :- \\+ (depends_on(I, D), \\+ done(D)).
eligible(I)  :- open_issue(I), satisfied(I).
blocked(I)   :- open_issue(I), \\+ satisfied(I).
waiting_on(I, D) :- depends_on(I, D), \\+ done(D).
blockers(I, Ds) :- setof(D, waiting_on(I, D), Ds).

phase_rank(I, R) :- phase(P, L), nth0(Idx, L, I), R is P * 100 + Idx.
next(I) :- setof(R-I, (eligible(I), phase_rank(I, R)), [_-I|_]).
queue(Q) :- setof(R-I, (eligible(I), phase_rank(I, R)), Q).

epic_progress(E, DoneCount, Total) :-
    epic_children(E, Cs),
    length(Cs, Total),
    include([C]>>done(C), Cs, Ds),
    length(Ds, DoneCount).

open_pr(P) :- pr(P, _, open, _, _).
stale_ci(P) :-
    pr(P, _, _, D, _),
    D \\== none,
    master_last_merge(M),
    D @< M.
missing_ci(P) :- open_pr(P), pr(P, _, _, none, _).
"""


@dataclass(frozen=True)
class GhIssue:
    number: int
    priority: int | None
    title: str
    body: str
    closed: bool


def parse_depends(body: str | None) -> list[int]:
    if not body:
        return []
    ids: list[int] = []
    for line in body.splitlines():
        if not re.match(r"\s*Depends on:", line, re.IGNORECASE):
            continue
        for match in re.finditer(r"#(\d+)", line):
            ids.append(int(match.group(1)))
    return ids


def parse_parent(body: str | None) -> int | None:
    if not body:
        return None
    match = re.search(r"^\s*Parent(?:\s+epic)?:\s*#(\d+)", body, re.MULTILINE | re.IGNORECASE)
    return int(match.group(1)) if match else None


def parse_priority(title: str) -> int | None:
    match = re.match(r"^P([0-3])\b", title)
    return int(match.group(1)) if match else None


def _escape(title: str) -> str:
    return title.replace("\\", "\\\\").replace('"', '\\"')


def _preserve(existing: str, predicate: str) -> list[str]:
    kept = []
    for line in existing.splitlines():
        if line.startswith(predicate):
            kept.append(line)
    return kept


def render_backlog(issues: list[GhIssue], phases: list[str], master_last_merge: str,
                   open_prs: list[str] | None = None) -> str:
    issues = sorted(issues, key=lambda i: i.number)
    open_issues = [i for i in issues if not i.closed]

    edges = sorted(
        {(i.number, dep) for i in open_issues for dep in parse_depends(i.body)}
    )
    parent_of = {i.number: parse_parent(i.body) for i in issues}
    epic_children: dict[int, list[int]] = {}
    for child, parent in parent_of.items():
        if parent is not None:
            epic_children.setdefault(parent, []).append(child)

    referenced: set[int] = {dep for _, dep in edges}
    for plist in epic_children.values():
        referenced.update(plist)
    for line in phases:
        referenced.update(int(m) for m in re.findall(r"\d+", line))

    closed_ids = sorted(i.number for i in issues if i.closed and i.number in referenced)

    out = [HEADER]
    if closed_ids:
        out.append("\n% Closed issues referenced by dependency edges, phases or epics.\n")
        out.append(" ".join(f"closed({n})." for n in closed_ids) + "\n")

    out.append("\n% Open issues: issue(Id, Priority, Status, ShortTitle).\n")
    for issue in open_issues:
        priority = issue.priority
        if priority is None:
            continue
        out.append(
            f'issue({issue.number}, p{priority}, open, "{_escape(issue.title)}").\n'
        )

    out.append("\n% Roadmap order: phase(N, OrderedIssueIds). Rank = N*100 + index.\n")
    for line in sorted(phases, key=lambda l: int(re.search(r"\d+", l).group())):
        out.append(line + "\n")

    out.append("\n% Dependency edges (only edges that gate eligibility).\n")
    for child, dep in edges:
        out.append(f"depends_on({child}, {dep}).\n")

    out.append("\n% Epics: epic_children(EpicId, ChildIds).\n")
    for parent in sorted(epic_children):
        children = sorted(epic_children[parent])
        out.append(f"epic_children({parent}, [{','.join(str(c) for c in children)}]).\n")

    out.append("\n% Open PRs: pr(Id, Issue, Status, CiDate, Note). CiDate = none | Y-M-D.\n")
    for line in sorted(open_prs or []):
        out.append(line + "\n")

    out.append(f"\nmaster_last_merge({master_last_merge}).\n")
    out.append(RULES)
    return "".join(out)


def fetch_issues(repo: str) -> list[GhIssue]:
    proc = subprocess.run(
        ["gh", "api", "--paginate",
         f"repos/{repo}/issues?state=all&per_page=100"],
        capture_output=True, text=True, check=True,
    )
    entries = json.loads(proc.stdout)
    issues = []
    for entry in entries:
        if "pull_request" in entry:
            continue
        title = entry.get("title") or ""
        issues.append(GhIssue(
            number=entry["number"],
            priority=parse_priority(title),
            title=title,
            body=entry.get("body") or "",
            closed=entry.get("state") == "closed",
        ))
    return issues


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default="lost-rob0t/zara")
    parser.add_argument("--date", default=datetime.date.today().isoformat())
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    existing = BACKLOG.read_text() if BACKLOG.exists() else ""
    phases = _preserve(existing, "phase(")
    open_prs = _preserve(existing, "pr(")

    issues = fetch_issues(args.repo)
    rendered = render_backlog(issues, phases, args.date, open_prs)

    if args.dry_run:
        sys.stdout.write(rendered)
        return 0

    BACKLOG.write_text(rendered)
    print(f"wrote {BACKLOG} ({len(issues)} issues imported)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
