package ai.zara.app.ui

import ai.zara.app.prolog.PrologFormBuilder
import ai.zara.app.prolog.PrologSource
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.heightIn
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp

@Composable
internal fun PrologStructuredBuilderPane(
    sources: List<PrologSource>,
    operationBusy: Boolean,
    onSaveSource: (String, String) -> Unit,
) {
    var targetFile by rememberSaveable { mutableStateOf("knowledge.pl") }
    var predicate by rememberSaveable { mutableStateOf("signal") }
    var arguments by rememberSaveable { mutableStateOf("entity:atom, value:atom") }
    var factValues by rememberSaveable { mutableStateOf("alice, red") }
    var ruleBody by rememberSaveable { mutableStateOf("signal(Entity, Value), Result = Value") }
    var generated by rememberSaveable { mutableStateOf("") }
    var builderError by rememberSaveable { mutableStateOf<String?>(null) }
    val tokens = LocalZaraTokens.current

    fun appendGenerated(source: String) {
        val normalizedTarget = targetFile.trim()
        if (!normalizedTarget.matches(Regex("[A-Za-z][A-Za-z0-9_-]{0,63}\\.pl"))) {
            builderError = "Target must be a private .pl basename"
            return
        }
        val existing = sources.firstOrNull { it.name == normalizedTarget }?.text.orEmpty()
        val next = buildString {
            if (existing.isNotBlank()) append(existing.trimEnd()).append("\n\n")
            append(source.trim()).append('\n')
        }
        builderError = null
        onSaveSource(normalizedTarget, next)
    }

    SectionCard("STRUCTURED PROLOG TOOLS") {
        MutedNotice("Facts, typed schemas, and rules compile to ordinary editable Prolog. Every save still crosses the workspace authority validator before Trealla sees it.")
        OutlinedTextField(
            value = targetFile,
            onValueChange = { targetFile = it },
            modifier = Modifier.fillMaxWidth(),
            label = { Text("Target source (.pl)") },
            singleLine = true,
        )
        OutlinedTextField(
            value = predicate,
            onValueChange = { predicate = it },
            modifier = Modifier.fillMaxWidth(),
            label = { Text("Predicate") },
            singleLine = true,
        )
        OutlinedTextField(
            value = arguments,
            onValueChange = { arguments = it },
            modifier = Modifier.fillMaxWidth(),
            label = { Text("Arguments · name:type") },
            supportingText = { Text("atom · integer · number · string · list · term") },
            singleLine = true,
        )
        OutlinedTextField(
            value = factValues,
            onValueChange = { factValues = it },
            modifier = Modifier.fillMaxWidth(),
            label = { Text("Fact values") },
            supportingText = { Text("atoms, numbers, quoted text, or lists") },
        )
        OutlinedTextField(
            value = ruleBody,
            onValueChange = { if (it.length <= 4_096) ruleBody = it },
            modifier = Modifier.fillMaxWidth().heightIn(min = 120.dp),
            label = { Text("Rule body") },
        )
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            SecondaryAction("Preview schema", !operationBusy) {
                generated = runCatching {
                    PrologFormBuilder.schema(predicate, PrologFormBuilder.parseArguments(arguments))
                }.onFailure { builderError = it.message }.getOrDefault("")
                if (generated.isNotBlank()) builderError = null
            }
            SecondaryAction("Preview fact", !operationBusy) {
                generated = runCatching {
                    PrologFormBuilder.fact(predicate, PrologFormBuilder.parseFactValues(factValues))
                }.onFailure { builderError = it.message }.getOrDefault("")
                if (generated.isNotBlank()) builderError = null
            }
        }
        PrimaryAction("Preview rule", !operationBusy) {
            generated = runCatching {
                PrologFormBuilder.rule(predicate, PrologFormBuilder.parseArguments(arguments), ruleBody)
            }.onFailure { builderError = it.message }.getOrDefault("")
            if (generated.isNotBlank()) builderError = null
        }
        builderError?.let { message -> ErrorBanner(message) }
    }

    if (generated.isNotBlank()) {
        SectionCard("BUILDER OUTPUT") {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text(
                    generated,
                    color = tokens.text,
                    fontFamily = FontFamily.Monospace,
                )
                PrimaryAction("Append, validate & reload", !operationBusy) {
                    appendGenerated(generated)
                }
            }
        }
    }
}
